services:
  postgres:
    image: postgres:13.3
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=task-flow